apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-dns
  name: coredns-external
  namespace: kube-system
spec:
  ports:
  - name: dns
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 172.18.255.241