apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meshmesh.fullname" . }}
  labels:
    {{- include "meshmesh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "meshmesh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "meshmesh.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "meshmesh.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - "--cluster-name={{ .Values.clusterName }}"
          - "--gossip-node-name={{ .Values.clusterName }}"
          - "--gossip-advertise-addr={{ .Values.gossip.advertiseAddress }}"
          - "--gossip-advertise-port={{ .Values.gossip.advertisePort }}"
          - "--gossip-bind-addr={{ .Values.gossip.bindAddress }}"
          - "--gossip-port={{ .Values.gossip.bindPort }}"
          - "--gossip-join-servers={{- join "," .Values.gossip.joinServers }}"
          ports:
            - name: gossip
              containerPort: {{ .Values.gossip.bindPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
