---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "meshmesh.fullname" . }}-role
rules:
  - apiGroups:
      - v1
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - v1
    resources:
      - daemonsets
    verbs:
      - patch
  - apiGroups:
      - v1
    resources:
      - services
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "meshmesh.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "meshmesh.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

