apiVersion: v1
kind: Service
metadata:
  name: {{ include "meshmesh.fullname" . }}
  labels:
    {{- include "meshmesh.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.gossip.advertiseAddress }}
  ports:
    - protocol: TCP
      port: {{ .Values.gossip.advertisePort }}
      targetPort: {{ .Values.gossip.bindPort }}
      name: gossip-tcp
  selector:
    {{- include "meshmesh.selectorLabels" . | nindent 4 }}
